### ISSUE TITLE
Using Hybrid Flow in Angular 2?

### ISSUE THREAD

**Issue by gulatiy** [jmurphzyo/Angular2OidcClient#23]
Hi @jmurphzyo, first of all thanks for the amazing work you have done.

I am building an angular 2 app with hybrid flow, it would be a great help if you can please guide/suggest on how to achieve that.
I have taken a look at this example and i understand a few things in auth.service.ts file and i understand that it is made for implicit flow if i am right.
 Waiting for your reply :-)

**Comment by jmurphzyo** [comment]
you're right but hybrid flow would be outside the scope of this lib, since implicit is pretty much the standard for spa's. you can check out identityservers examples for how they implement hybrid flow using .net.

**Comment by santialbo** [comment]
@jmurphzyo ask this on a closed issue but this seems a little related to my doubts. If I'm developing an Angular SPA that talks to an backend API, what you are saying is that the IDP should implement the Implicit flow, and not the Hybrid?

Is the objective of Hybrid meant to be used by server rendered applications so that the access_token is not leaked to the browser?

**Comment by jmurphzyo** [comment]
@santialbo from what I understand that seems like the just of it but I am by no means an expert. I would find someone more knowledgeable than me. Maybe check out stavkoverflow.
